# Generated by Django 4.2.4 on 2023-08-17 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(max_length=5000)),
                ('category', models.CharField(choices=[('news', 'news'), ('politics', 'politics'), ('business', 'business'), ('entertainment', 'entertainment'), ('sports', 'sports'), ('technology', 'technology'), ('opinion', 'opinion'), ('lifestyle', 'lifestyle'), ('gallery', 'gallery'), ('obituary', 'obituary')], default='news', max_length=100)),
                ('image', models.ImageField(default='def.jpg', upload_to='images')),
                ('video', models.FileField(default='vid.jpg', upload_to='TM/Scheme_video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('type', models.CharField(choices=[('image', 'image'), ('video', 'video')], default='image', max_length=50)),
                ('tags', models.CharField(max_length=300)),
                ('source', models.CharField(max_length=300)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
