# Generated by Django 4.2.4 on 2023-08-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_post_image_alter_program_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='program',
            name='start_date',
        ),
        migrations.AddField(
            model_name='program',
            name='end_time',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AddField(
            model_name='program',
            name='prog_day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='start_time',
            field=models.TimeField(default='12:00:00'),
        ),
    ]
