# Generated by Django 4.2.4 on 2023-08-21 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_remove_program_end_date_remove_program_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='program',
            name='prog_day',
        ),
        migrations.RemoveField(
            model_name='program',
            name='start_time',
        ),
        migrations.AddField(
            model_name='program',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='program',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
