# Generated by Django 4.2.4 on 2023-08-22 12:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_remove_program_end_time_remove_program_prog_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Video'),
        ),
    ]
