# Generated by Django 4.2.4 on 2023-08-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='impressions',
            field=models.IntegerField(default=0),
        ),
    ]
